"""Research backtest."""

from quantlab.backtest.benchmark import (
    BenchmarkComparison,
    align_returns,
    compare_benchmark,
    equal_weight_returns_from_frame,
    returns_from_closes,
    strategy_daily_returns,
)
from quantlab.backtest.engine import (
    MISSING_PRICE_POLICY,
    run_backtest,
    weekly_signal_dates,
)
from quantlab.backtest.lifecycle import (
    DELIST_DATE_IS_FIRST_INVALID_V1,
    LEGACY_DELIST_DATE_INCLUSIVE,
    LifecycleMonitor,
    first_invalid_open_session,
    is_instrument_invalid_on_delist_boundary,
)
from quantlab.backtest.metrics import compute_metrics
from quantlab.backtest.models import (
    RUN_MODE_DIAGNOSTIC,
    RUN_MODE_STRICT,
    STATUS_ACCOUNTING_ERROR,
    STATUS_BLOCKED_UNSUPPORTED_EVENT,
    STATUS_COMPLETED,
    STATUS_COMPLETED_WITH_SETTLEMENT,
    AccountingResidual,
    BacktestConfig,
    BacktestResult,
    BookSnapshot,
    DailyBacktestRecord,
    DelistingSettlementConfig,
    FailedAttempt,
    LifecycleEvent,
    PositionRecord,
    RebalanceRecord,
    RiskPolicyAuditRecord,
    SettlementRecord,
    SkippedExecution,
    TradeRecord,
)
from quantlab.backtest.report import build_report
from quantlab.backtest.risk_policy import (
    EXIT_POLICY_ID,
    EXIT_POLICY_NAME,
    EXIT_POLICY_VERSION,
    risk_policy_statistics,
    termination_decisions_available_as_of,
)

__all__ = [
    "AccountingResidual",
    "BacktestConfig",
    "BacktestResult",
    "BenchmarkComparison",
    "BookSnapshot",
    "DELIST_DATE_IS_FIRST_INVALID_V1",
    "DailyBacktestRecord",
    "DelistingSettlementConfig",
    "FailedAttempt",
    "LEGACY_DELIST_DATE_INCLUSIVE",
    "LifecycleEvent",
    "LifecycleMonitor",
    "MISSING_PRICE_POLICY",
    "PositionRecord",
    "RebalanceRecord",
    "RiskPolicyAuditRecord",
    "RUN_MODE_DIAGNOSTIC",
    "RUN_MODE_STRICT",
    "SettlementRecord",
    "SkippedExecution",
    "STATUS_ACCOUNTING_ERROR",
    "STATUS_BLOCKED_UNSUPPORTED_EVENT",
    "STATUS_COMPLETED",
    "STATUS_COMPLETED_WITH_SETTLEMENT",
    "TradeRecord",
    "EXIT_POLICY_ID",
    "EXIT_POLICY_NAME",
    "EXIT_POLICY_VERSION",
    "align_returns",
    "build_report",
    "compare_benchmark",
    "compute_metrics",
    "equal_weight_returns_from_frame",
    "first_invalid_open_session",
    "is_instrument_invalid_on_delist_boundary",
    "returns_from_closes",
    "run_backtest",
    "risk_policy_statistics",
    "strategy_daily_returns",
    "termination_decisions_available_as_of",
    "weekly_signal_dates",
]
